### ISSUE TITLE
Issue in the EPUB examples, not following the same order than the PDF and some don't appear

### ISSUE THREAD

**Issue by unxavi** [twoscoops/two-scoops-of-django-1.5#1]
Noticed there's is differences between the PDF and the EPUB... for example chapter 9, to be more accurate:
- 9.6 Pattern 5: Reusable Search Mixin View

On the PDF the first example is 9.13 on the EPUB is 9.12 because chapters before the EPUB never show up some examples  and continue on the EPUB the example 9.13 is totally empty.

I attach a couple of  images to illustrate what I mean:

-PDF screenshot:

![pdf](https://f.cloud.github.com/assets/3817679/1020322/e449fb1c-0c8c-11e3-98a6-ac325afe0472.png)

-EPUB screenshot:

![epub](https://f.cloud.github.com/assets/3817679/1020323/ee9bb8ee-0c8c-11e3-8d7f-def8e39fcb65.png)

.

**Comment by pydanny** [comment]
Apologies, but we could never figure this out.
