### ISSUE TITLE
Issue with example 16.9

### ISSUE THREAD

**Issue by johnzimmerman** [twoscoops/two-scoops-of-django-1.5#3]
In your book on page 164 in the TwoScoopsUserChangeForm class, you have:

password = ReadOnlyPasswordHashField()
    class Meta:
        model = TwoScoopsUser
    def clean_password(self):
        # Regardless of what the user provides, return the
        # initial value. This is done here, rather than on
        # the field, because the field does not have access
        # to the initial value
        return self.initial["password”]

If I make no changes to my custom user model through the admin and click save, a log history record is still created that says "Changed password." The only way I can get it to stop is by commenting out the line `password = ReadOnlyPasswordHashField()`, but then the field can be changed. Do you have any suggestions on why this might be happening or how I can stop it? Thank you.

**Comment by johnzimmerman** [comment]
It looks like this is a bug in the Django source and was noted [here](https://code.djangoproject.com/ticket/18460). The fix was put into 1.6. I verified that it works by running the same code in v1.6 RC1.

**Comment by pydanny** [comment]
Wow! Nice detective work!
