### ISSUE TITLE
Example 9.13 is empty

### ISSUE THREAD

**Issue by lachezar** [twoscoops/two-scoops-of-django-1.5#5]
![image](https://f.cloud.github.com/assets/130336/1819308/140a67de-7082-11e3-94dd-e9b1a15c3d0f.jpg)

There is no code sample for example section 9.13 on the epub version.

**Comment by lachezar** [comment]
I just noticed that there is a general issue about this.

**Comment by pydanny** [comment]
Hi @lucho-yankov - the content of the 1.5 edition of the book is frozen on account of us working on the forthcoming 1.6 edition!
