### ISSUE TITLE
Example 11.7 csrftoken is not defined

### ISSUE THREAD

**Issue by frattallone** [twoscoops/two-scoops-of-django-1.5#6]
Csrftoken is not defined but reading the link you provide (https://docs.djangoproject.com/en/1.5/ref/contrib/csrf/) is possible to understand how to fix it.

Acquiring the token is straightforward:

// using jQuery
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');

The above code could be simplified by using the jQuery cookie plugin to replace getCookie:

var csrftoken = $.cookie('csrftoken');

**Comment by pydanny** [comment]
Addressed in TSD 1.6.
