### ISSUE TITLE
Typo in in example 5.8 (Setting secret key as environment variable in virtualenv activate)

### ISSUE THREAD

**Issue by willdearman** [twoscoops/two-scoops-of-django-1.5#7]
In Example 5.8 (page 35 of the 1.5 Book)  the secret key needs a single quote before and after the key value in order to work correctly in the virtualenv activate file. 

Without the single quotes you get an error when activating the environment. I'm not sure if this always happens, the left parenthesis in my key value was unexpected.

**Comment by pydanny** [comment]
I believe this was fixed in a later edition of the book.
