### ISSUE TITLE
Error in Example 5.9 (Set secret key as environment variable in Windows Virtualenv)

### ISSUE THREAD

**Issue by willdearman** [twoscoops/two-scoops-of-django-1.5#8]
For example 5.9 on page 36, `setx` does not appear to work for this type of environmental variable (in Win 8.1). Also, there need to be quotation marks. 

I was able to get it to work using this syntax:
`set "SOME_SECRET_KEY=1c3-cr3am-15-yummy"`
in the activate.bat for my virtual environment.

**Comment by pydanny** [comment]
I believe this was fixed in a later edition of the book.
